services:
  core:
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_core
    command: start web
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "1"
          # memory: 1536M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  celery:
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_celery
    command: start task
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.2"
          # memory: 1024M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  koko:
    image: jumpserver/jms_koko:${VERSION}
    container_name: jms_koko
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "check http://localhost:5000/koko/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT:-2222}
    networks:
      - net

  guacd:
    image: jumpserver/guacd:1.5.5-bookworm
    container_name: jms_guacd
    user: root
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      GUACD_LOG_LEVEL: ${GUACD_LOG_LEVEL:-error}
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  lion:
    image: jumpserver/jms_lion:${VERSION}
    container_name: jms_lion
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "check http://localhost:8081/lion/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  magnus:
    image: jumpserver/jms_magnus:${VERSION}
    container_name: jms_magnus
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "check http://localhost:8088/health"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/magnus/data:/opt/magnus/data
    ports:
      - ${MAGNUS_MYSQL_PORT:-33061}:33061
      - ${MAGNUS_MARIADB_PORT:-33062}:33062
      - ${MAGNUS_REDIS_PORT:-63790}:63790
    networks:
      - net

  chen:
    image: jumpserver/jms_chen:${VERSION}
    container_name: jms_chen
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
    healthcheck:
      test: "check http://localhost:8082/chen"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  kael:
    image: jumpserver/jms_kael:${VERSION}
    container_name: jms_kael
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    volumes:
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
    healthcheck:
      test: "check http://localhost:8083/kael/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  web:
    image: jumpserver/jms_web:${VERSION}
    container_name: jms_web
    deploy:
      mode: replicated
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    healthcheck:
      test: "check http://localhost/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/web/data/logs:/var/log/nginx
      - ${VOLUME_DIR}/web/download:/opt/download
    ports:
      - ${HTTP_PORT:-80}:80
    networks:
      - net