name: Docker Compose Image CI

on:
  push:
    # branches:
      # - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get_tag
      run: |
        TAG=$(basename ${GITHUB_REF})
        echo "::set-output name=TAG::$TAG"
    - name: Set Config
      run: cp config_example.conf .env
    - name: Update Version
      run: sed -i "s/Version=.*/Version=${{ steps.get_tag.outputs.TAG }}/g" .env
    - name: Build Docker-Compose image
      run: docker-compose --file docker-compose-build.yml build
    - name: Docker Tag Rename
      run: |
        docker tag jumpserver/jms_mysql:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_mysql:latest
        docker tag jumpserver/jms_redis:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_redis:latest
        docker tag jumpserver/jms_nginx:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_nginx:latest
        docker tag jumpserver/jms_core:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_core:latest
        docker tag jumpserver/jms_koko:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_koko:latest
        docker tag jumpserver/jms_guacamole:${{ steps.get_tag.outputs.TAG }} jumpserver/jms_guacamole:latest
    - name: Logo into Docker registry
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u wojiushixiaobai --password-stdin
    - name: Push image to Docker registry
      run: |
        docker push jumpserver/jms_mysql:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_redis:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_nginx:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_core:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_koko:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_guacamole:${{ steps.get_tag.outputs.TAG }}
        docker push jumpserver/jms_mysql:latest
        docker push jumpserver/jms_redis:latest
        docker push jumpserver/jms_nginx:latest
        docker push jumpserver/jms_core:latest
        docker push jumpserver/jms_koko:latest
        docker push jumpserver/jms_guacamole:latest
    - name: Logo into HuaweiCloud registry
      run: echo "${{ secrets.HW_CLOUD_TOKEN }}" | docker login -u cn-south-1@TZZDVNMCLUKINTT3FMLI swr.cn-south-1.myhuaweicloud.com --password-stdin
    - name: Push image to HuaweiCloud registry
      run: |
        docker tag jumpserver/jms_mysql:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_mysql:${{ steps.get_tag.outputs.TAG }}
        docker tag jumpserver/jms_redis:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_redis:${{ steps.get_tag.outputs.TAG }}
        docker tag jumpserver/jms_nginx:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_nginx:${{ steps.get_tag.outputs.TAG }}
        docker tag jumpserver/jms_core:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_core:${{ steps.get_tag.outputs.TAG }}
        docker tag jumpserver/jms_koko:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_koko:${{ steps.get_tag.outputs.TAG }}
        docker tag jumpserver/jms_guacamole:${{ steps.get_tag.outputs.TAG }} swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_guacamole${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_mysql:${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_redis:${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_nginx:${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_core:${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_koko:${{ steps.get_tag.outputs.TAG }}
        docker push swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_guacamole${{ steps.get_tag.outputs.TAG }}
