name: Nginx Image Buildx

on:
  push:
    # branches:
      # - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get_tag
      run: |
        TAG=$(basename ${GITHUB_REF})
        echo "::set-output name=TAG::$TAG"

    - name: Build Nginx
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: wojiushixiaobai/jms_web
        dockerUser: wojiushixiaobai
        dockerPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: web/Dockerfile
        platform: linux/amd64,linux/arm64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}

    - name: Build Nginx for JumpServer
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: jumpserver/jms_web
        dockerUser: wojiushixiaobai
        dockerPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: web/Dockerfile
        platform: linux/amd64,linux/arm64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}

    - name: Build Nginx for GitHub
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        dockerServer: ghcr.io
        imageName: ghcr.io/wojiushixiaobai/jms_web
        dockerUser: wojiushixiaobai
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: web/Dockerfile
        platform: linux/amd64,linux/arm64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}
